url: https://rust.code-maven.com
repo: https://github.com/szabgab/rust.code-maven.com
branch: main
site_name: Rust programming language
author_name: Gábor Szabó
link_to_source: true
footer: Get extra content and notifications in the [Rust Maven newsletter](/subscribe)!.
tags:
  title: Tags
  description: Articles about Rust with tags
google_analytics: G-F3V82JBHQE

authors:
  - name: Gabor Szabo
    nickname: szabgab
    picture: szabgab.png

show_related: true
related_pages_title: Related Pages

from:
  name: Gabor Szabo
  email: gabor@szabgab.com
archive:
  title: Archive
  description: List of all the articles about the Rust programming language

atom:
  max: 20

navbar:
  start:
    - path: /
      title: Home
    - path: /tags/
      title: Tags
    - path: /slides/rust/
      title: Slides
    - path: /subscribe
      title: Newsletter
    - path: /projects
      title: Projects
    - path: /training-course
      title: Training
  end:
    - path: /archive
      title: Archive
    - path: /about
      title: About

